[integration]
name = "Google Drive"
version = "0.0.1"
icon = "logos:google-drive"
description = "Integrate with Google Drive to streamline file management, sharing, and collaboration directly within your workflows."
categories = ["app"]
authors = ["Wakflo <integrations@wakflo.com>"]
