package shared

import (
	"github.com/juicycleff/smartform/v1"
)

var CourierCodes = []*smartform.Option{
	{Value: "fedex", Label: "FedEx"},
	{Value: "ups", Label: "UPS"},
	{Value: "usps", Label: "USPS"},
	{Value: "dhl", Label: "DHL"},
	{Value: "speedaf", Label: "Speedaf"},
	{Value: "ontrac", Label: "OnTrac"},
	{Value: "lasership", Label: "LaserShip"},
	{Value: "tforce", Label: "TForce"},
	{Value: "rrdonnelley", Label: "RR Donnelley"},
	{Value: "estes", Label: "Estes"},
	{Value: "old_dominion", Label: "Old Dominion Freight Line"},
	{Value: "saia", Label: "Saia"},
	{Value: "xpo", Label: "XPO Logistics"},
	{Value: "forward_air", Label: "Forward Air"},
	{Value: "speedee", Label: "SpeeDee Delivery"},
	{Value: "gso", Label: "GSO (Golden State Overnight)"},
	{Value: "tnt", Label: "TNT"},
	{Value: "pitney_bowes", Label: "Pitney Bowes"},
	{Value: "purolator", Label: "Purolator"},
	{Value: "newgistics", Label: "Newgistics"},
	{Value: "yrc_freight", Label: "YRC Freight"},
	{Value: "land_air", Label: "Land Air Express"},
	{Value: "u_ship", Label: "uShip"},
	{Value: "xpress_global", Label: "Xpress Global Systems"},
	{Value: "daylight_transport", Label: "Daylight Transport"},
	{Value: "r_l_carriers", Label: "R+L Carriers"},
	{Value: "central_transport", Label: "Central Transport"},
	{Value: "southeastern_freight", Label: "Southeastern Freight Lines"},
	{Value: "ward_trucking", Label: "Ward Trucking"},
	{Value: "cross_country", Label: "Cross Country Courier"},
	{Value: "gls", Label: "GLS"},
	{Value: "roadrunner", Label: "Roadrunner Transportation"},
	{Value: "aaa_cooper", Label: "AAA Cooper Transportation"},
	{Value: "dohrn_transfer", Label: "Dohrn Transfer"},
	{Value: "rwc", Label: "RWC (Regional West)"},
	{Value: "brown_integrated", Label: "Brown Integrated Logistics"},
	{Value: "forwardair", Label: "Forward Air"},
	{Value: "r_l_freight", Label: "R+L Global Logistics"},
	{Value: "sudden_valley", Label: "Sudden Valley"},
	{Value: "best_overland", Label: "Best Overland Freight"},
	{Value: "western_freight", Label: "Western Freight"},
	{Value: "americold", Label: "Americold"},
	{Value: "allied_express", Label: "Allied Express"},
	{Value: "yellow_corp", Label: "Yellow Corporation"},
	{Value: "safelite", Label: "Safelite"},
	{Value: "mainfreight", Label: "Mainfreight"},
	{Value: "dynamex", Label: "Dynamex"},
	{Value: "hermes", Label: "Hermes"},
	{Value: "ups_freight", Label: "UPS Freight"},
	{Value: "fedex_ground", Label: "FedEx Ground"},
	{Value: "usps_priority", Label: "USPS Priority Mail"},
	{Value: "china-post", Label: "China Post"},
	{Value: "china-ems", Label: "China EMS"},
	{Value: "postnord", Label: "PostNord"},
	{Value: "fastway_uk", Label: "Fastway UK"},
	{Value: "xpo_logistics", Label: "XPO Logistics"},
	{Value: "dpd_canada", Label: "DPD Canada"},
	{Value: "intime_express", Label: "InTime Express"},
	{Value: "p4d", Label: "P4D (UK)"},
	{Value: "frakt24", Label: "Frakt24"},
	{Value: "bring_express", Label: "Bring Express"},
	{Value: "mbe_canada", Label: "MBE Canada"},
	{Value: "chit_chat_express", Label: "Chit Chat Express"},
	{Value: "gophr", Label: "Gophr"},
	{Value: "city_sprint", Label: "City Sprint"},
	{Value: "purolator_courier", Label: "Purolator Courier"},
	{Value: "logistics_xpress", Label: "Logistics Xpress"},
	{Value: "ceva_logistics", Label: "CEVA Logistics"},
	{Value: "cool_express", Label: "Cool Express"},
	{Value: "hong-kong-post", Label: "Hong Kong Post"},
	{Value: "singapore-post", Label: "Singapore Post"},
	{Value: "swiss-post", Label: "Swiss Post"},
	{Value: "royal-mail", Label: "Royal Mail"},
	{Value: "postnl-parcels", Label: "PostNL International"},
	{Value: "canada-post", Label: "Canada Post"},
	{Value: "australia-post", Label: "Australia Post"},
	{Value: "new-zealand-post", Label: "New Zealand Post"},
	{Value: "parcel-force", Label: "Parcelforce"},
	{Value: "belgium-post", Label: "Bpost"},
	{Value: "brazil-correios", Label: "Brazil Correios"},
	{Value: "russian-post", Label: "Russian Post"},
	{Value: "malaysia-post", Label: "Malaysia Post"},
	{Value: "maldives-post", Label: "Maldives Post"},
	{Value: "malta-post", Label: "Malta Post"},
	{Value: "mauritius-post", Label: "Mauritius Post"},
	{Value: "correos-mexico", Label: "Mexico Post"},
	{Value: "moldova-post", Label: "Moldova Post"},
	{Value: "la-poste-monaco", Label: "Monaco Post"},
	{Value: "monaco-ems", Label: "Monaco EMS"},
	{Value: "mongol-post", Label: "Mongol Post"},
	{Value: "posta-crne-gore", Label: "Montenegro Post"},
}
