[integration]
name = "Claude AI"
description = """Integrate your Claude website builder with our workflow automation software to streamline content creation and deployment. Automate tasks such as publishing new pages, updating existing ones, and triggering workflows based on page changes. Seamlessly connect your Claude site to other tools and services, enabling a more efficient and collaborative content management process."""
version = "0.0.1"
icon = "material-icon-theme:claude"
categories = ["ai"]
authors = ["Wakflo <integrations@wakflo.com>"]