[integration]
name = "Jira Cloud"
description = """Integrate your workflow automation software with Jira Cloud to streamline your development process and enhance collaboration. Seamlessly connect workflows, automate tasks, and gain real-time visibility into project status. With this integration, you can:

* Automate repetitive tasks and reduce manual errors
* Trigger custom workflows based on Jira issue updates
* Sync Jira issues with workflow automation software for real-time tracking
* Gain insights into project performance and identify areas for improvement
* Enhance collaboration by automating notifications and approvals

Elevate your development process with this powerful integration, and experience the benefits of streamlined workflows, increased productivity, and improved team efficiency."""
version = "0.0.1"
icon = "logos:jira"
categories = ["app"]
authors = ["Wakflo <integrations@wakflo.com>"]
